select_source_playlist:
  target:
    entity:
      domain: media_player
      integration: philips_dline_sicp
  fields:
    source:
      required: true
      example: "Media Player"
      selector:
        text:
    playlist:
      default: 0
      selector:
        number:
          min: 0
          max: 8
          mode: box

set_brightness:
  target:
    entity:
      domain: media_player
      integration: philips_dline_sicp
  fields:
    brightness:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_contrast:
  target:
    entity:
      domain: media_player
      integration: philips_dline_sicp
  fields:
    contrast:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

send_raw_command:
  fields:
    cmd:
      required: true
      example: "0x45"
      selector:
        text:
    data:
      example: "0D 09 01 00"
      selector:
        text:
    host:
      example: "192.168.1.120"
      selector:
        text:
